server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone : http://insane-service-registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: raksha
            client-secret: 438FzgvSk0ywjD3j46a2gitOWgTbQs8T
            authorization-grant-type: authorization_code
            scope: openid,profile,email,addresses,genders
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://keycloak.insane.com:8080/realms/raksha
            user-name-attribute: preferred_username
      resourceserver:
        opaquetoken:
          introspection-uri: http://keycloak.insane.com:8080/realms/raksha/protocol/openid-connect/token/introspect

          client-id: raksha
          client-secret: 438FzgvSk0ywjD3j46a2gitOWgTbQs8T
  application:
    name: insane-oauth2-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: insane-resource-provider
          uri: lb://insane-resource-provider
          predicates:
            - Path=/resources/**
logging:
  level:
    org:
      springframework:
        security: DEBUG
app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect